name: ${SLIME_CLUSTER_NAME:-slime-training}

resources:
  cloud: ${SLIME_CLOUD:-aws}
  accelerators: ${SLIME_ACCELERATOR:-H100:8}
  instance_type: ${SLIME_INSTANCE_TYPE}
  use_spot: ${SLIME_USE_SPOT:-false}

num_nodes: ${SLIME_NUM_NODES:-1}

file_mounts:
  /slime_checkpoints:
    name: ${SLIME_CHECKPOINT_BUCKET:-slime-checkpoints}
    store: ${SLIME_STORAGE_TYPE:-s3}
    mode: MOUNT
  /slime_data:
    name: ${SLIME_DATA_BUCKET}
    store: ${SLIME_STORAGE_TYPE:-s3}
    mode: MOUNT
    
envs:
  PYTHONPATH: /root/Megatron-LM/
  CUDA_DEVICE_MAX_CONNECTIONS: "1"
  WANDB_API_KEY: ${WANDB_API_KEY}
  HF_TOKEN: ${HF_TOKEN}
  
setup: |
  set -ex
  
  sudo apt-get update
  sudo apt-get install -y git
  
  cd /root
  if [ ! -d "slime" ]; then
    git clone https://github.com/THUDM/slime.git
  else
    cd slime && git pull && cd ..
  fi
  cd slime
  pip install -e .
  
  if [ ! -d "/root/Megatron-LM" ]; then
    git clone https://github.com/NVIDIA/Megatron-LM.git /root/Megatron-LM
  fi
  
  if [ ! -z "${HF_MODEL_ID}" ] && [ ! -z "${MODEL_DIR}" ]; then
    pip install -U huggingface_hub
    mkdir -p ${MODEL_DIR}
    huggingface-cli download ${HF_MODEL_ID} --local-dir ${MODEL_DIR}
  fi

run: |
  cd /root/slime
  
  python train.py \
    --actor-num-nodes ${SLIME_NUM_NODES:-1} \
    --actor-num-gpus-per-node ${SLIME_GPUS_PER_NODE:-8} \
    ${SLIME_TRAIN_ARGS}
